[package]
authors = ["Roma Sokolov", "Alexander Zhuravlev", "Jorge Aparicio <jorge@japaric.io>"]
name = "mpu9250"
version = "0.4.2"
description = "no_std driver for the MPU9250 & onboard AK8963 (accelerometer + gyroscope +  magnetometer IMU)"
keywords = ["arm", "cortex-m", "stm32", "hal"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/copterust/mpu9250"

[dependencies]
embedded-hal = "0.2.0"
generic-array = "0.11.0"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.nalgebra]
default-features = false
version = "0.16.0"
