[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "mpu9250"
version = "0.1.0"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
git = "https://github.com/japaric/embedded-hal"
